### ISSUE TITLE
just read it

### ISSUE THREAD

**Issue by userlolhueue** [bui/taiko-web#257] opened 2020-07-20 20:23 UTC
﻿###### 下記の問題を説明してください。 スクリーンショットと診断情報を含めてください。
###### Describe the problem you are having below. Please include a screenshot and the diagnostic information.

are actually going to add our suggestions

**Comment by bui** [comment] 2020-07-20 21:56
This is an issue tracker. Your previous issue was closed as it is a duplicate of an existing issue. Please refrain from spamming

**Closed by bui** 2020-07-20 21:56 UTC
