### ISSUE TITLE
Controller D-pad not working while playing

### ISSUE THREAD

**Issue by SSurachet** [bui/taiko-web#155] opened 2019-05-25 10:45 UTC
My controller D-pad is working fine at menu and other place, but not while playing.

**Comment by bui** [comment] 2020-03-18 18:25
Hi @SSurachet,

Could you please confirm if this is still an issue? If so, please tell us what controller you're using.

**Comment by autisticboi** [comment] 2020-03-27 05:24
I am having the same issue as well. Am using some cheap china controller and the d pad is not working

**Comment by MengXiangxi** [comment] 2020-05-30 16:43
Hi! I have been trying to use a MIDI pad as the input. Taking the advantage of [Bome's MIDI Translator Classic](https://www.bome.com/products/mtclassic), I am able to simulate a key stroke perfectly. When I tried it on the webpage, the taiko icon shows to be hit upon pad trigger, but it just would not score. Meanwhile keyboard could hit and score.

I am wondering if this issue is related. Thank you!

**Comment by Beekiplier** [comment] 2020-07-20 13:13
Hi! I'm currently having the same problem where my d-pad won't work when I'm playing. My controller is a GT-006 Marvo Touch Wisdom. The controller itself works great in the menu, but when playing a song my d-pad does not work at all. Is there a solution?

**Comment by micjarrett** [comment] 2020-12-04 01:34
I am experiencing a similar issue.

Using a USB-connected MIDI interface, and mapping d,f,j & k keys to drum pads using MIDIKey2Key.
When I trigger the pads, I see the Taiki icon register the hit but the game does not score the hit, the pads also work for all song navigation tasks etc. Hitting my keyboard however during the song registers the score.
Opening up notepad etc. I can confirm the pads register the keys and do not hold or duplicate the key, so it should work the same way as a keyboard keypress.

**Comment by LoveEevee** [comment] 2020-12-05 04:03
@MengXiangxi I was able to reproduce your issue using [LoopBe1](https://www.nerds.de/en/loopbe1.html) and [FreePiano](https://freepiano.tiwb.com/en/) to send keyboard input to Bome's MIDI Translator Classic and it is now fixed in #294

@micjarrett I could not reproduce it with MIDIKey2Key, but I hope it also got fixed by itself

**Closed** 2022-02-17 19:29 UTC
