### ISSUE TITLE
No sound

### ISSUE THREAD

**Issue by hoqueenieho** [bui/taiko-web#239] opened 2020-06-08 06:23 UTC
No sound using Chrome and Safari browser in my iphone but it’s working using laptop computer.  May i know how to adjust sound in the browser using mobile?

**Comment by agneskoo** [comment] 2020-06-30 01:22
Me too. Suddenly no sound in mobile version but still work in Mac version.

**Comment by samsonllam** [comment] 2020-08-19 18:50
It seems the server has some errors to send the preview.mp3 file

![image](https://user-images.githubusercontent.com/17029792/90677153-88b53880-e28f-11ea-8d5b-921203bc094f.png)
![image](https://user-images.githubusercontent.com/17029792/90677229-a08cbc80-e28f-11ea-906f-9acbc2b20fb3.png)

**Comment by Animenosekai** [comment] 2021-04-26 17:26
Did you guys check your "Silent Mode" (the thing which you can enable and disable on the left) because it also makes the game silent.

**Comment by samsonllam** [comment] 2021-04-30 07:48
I think the issue is already been resolved in the few previous update. thankss

**Closed** 2022-02-17 19:26 UTC
