### ISSUE TITLE
balloon

### ISSUE THREAD

**Issue by mushiiowo** [bui/taiko-web#311] opened 2021-01-14 21:07 UTC
﻿###### 下記の問題を説明してください。 スクリーンショットと診断情報を含めてください。
###### Describe the problem you are having below. Please include a screenshot and the diagnostic informat

I'm not sure if this is just me but the balloon doesn't work. I rapidly press don and ka  ( in this case f d j and k) like I do on the NS taiko game however it is just not working. 

Thank you 
:)

```
Taiko-Web version: https://github.com/bui/taiko-web/commit/665fc57929b48c895f208b497ae71c84cd8cee57
URL: https://taiko.bui.pm/
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36 Edg/87.0.664.66
Screen size: 1368x802, outer: 1368x872, ratio: 2.00
Blur performance: 9ms, all images: 848ms
Page load: 7.9s
Language: en (en-GB, en, en-US)
Audio Latency: 0ms, Video Latency: 0ms
```

**Comment by LoveEevee** [comment] 2021-01-14 23:09
Duplicate of #109

**Closed by LoveEevee** 2021-01-14 23:09 UTC
